### ISSUE TITLE
fails if invoked from cloud functions

### ISSUE THREAD

**Issue by ralpheichelberger** [googleapis/nodejs-iot#193]
I am trying to send a command to a connected mqtt device from a google clould function using boilerplate code like this:
(with my real project and registery name)
```js
const iot = require('@google-cloud/iot');
const client = new iot.v1.DeviceManagerClient();
  let formattedName = client.devicePath("my-project", "europe-west1", "my_registry", deviceId);
  let binaryData = Buffer.from("some command");
  const request = {
    name: formattedName,
    binaryData: binaryData,
  };
  client.sendCommandToDevice(request)
    .then(responses => {
      const response = responses[0];
      console.log(response);
    })
    .catch(err => {
      console.error(err);
    });
```

This works fine if invoked locally but if a could function invokes this it gets stuck with following message:
```
Error: Getting metadata from plugin failed with error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500 at Http2CallStream.call.on (/srv/node_modules/@grpc/grpc-js/build/src/client.js:96:45) at emitOne (events.js:121:20) at Http2CallStream.emit (events.js:211:7) at process.nextTick (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22) at _combinedTickCallback (internal/process/next_tick.js:132:7) at process._tickDomainCallback (internal/process/next_tick.js:219:9) code: '500', details: 'Getting metadata from plugin failed with error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500', metadata: Metadata { options: undefined, internalRepr: Map {} }, note: 'Exception occurred in retry method that was not classified as transient'
```

I tried older version of the javascript library using googleapis directly. With cloud functions it failed saying I am using the api for the first time or didn't activate it for this project.
Now using this package the error is stranger still. 

I can't find any information about the issue and I am searching for weeks now.

Any hint what I could do to make iot core work with functions?

Best Regrads,
Ralph Eichelberger

**Comment by ralpheichelberger** [comment]
did you investigate that? - Is it me doing something wrong here?

**Comment by ralpheichelberger** [comment]
Still not possible to send a Message to a iot device:
client.projects.locations.registries.devices.sendCommandToDevice
returns "error: Error: Could not refresh access token: Unsuccessful response status code. Request failed with status code 500"
even if functions has all permissions
Cloud IoT-Administrator
Deployment Manager-Bearbeiter
Pub/Sub-Administrator
Storage-Objekt-Administrator

I don't know where to use DeviceManagerClient in that scope.

**Comment by ralpheichelberger** [comment]
I found a solution: you need to include a JSON key file like you would from an external host even it is all within the google cloud platform. So you can close it - thanks.
