### ISSUE TITLE
samples/manager wont work when serviceAccount option specified

### ISSUE THREAD

**Issue by amarkevich** [googleapis/nodejs-iot#344]
#### Environment details
  - OS: Windows 10 Enterprise (10.0.18363)
  - Node.js version: 12.16.2
  - npm version: 6.14.4
  - `@google-cloud/iot` version: "^2.0.0" from master

#### Steps to reproduce
  1. go to samples/manager
  2. npm install
  3. execute
`node manager.js listDevices devices -p PROJECT -c REGION -s PATH-TO/credentials.json
`
```
(node:9576) UnhandledPromiseRejectionWarning: Error: 400 undefined: Getting metadata from plugin failed with error: invalid_grant
    at Object.callErrorFromStatus (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
    at Object.onReceiveStatus (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\client.js:175:52)
    at Object.onReceiveStatus (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:341:141)
    at Object.onReceiveStatus (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\call-stream.js:155:22)
    at Http2CallStream.endCall (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\call-stream.js:141:18)
    at Http2CallStream.cancelWithStatus (c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\call-stream.js:450:14)
    at c:\project\nodejs-iot-master\samples\manager\node_modules\@grpc\grpc-js\build\src\channel.js:225:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Works only when GOOGLE_APPLICATION_CREDENTIALS environment variable is set to the same path.

**Comment by gguuss** [comment]
I've confirmed this, when the samples were migrated to the new client library, the code for setting the client library up with a parametrized path was disconnected. 

I think the right resolution here is to remove the parameter and require the path be set in an environment variable to match default application credentials for Cloud authentication.

If you're needing a quick work-around for the examples CLI, replace getClient with:

```node
const getClient = async serviceAccountJson => {
  // the getClient method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS
  // environment variables if serviceAccountJson is not passed in
  const iotClient = new iot.v1.DeviceManagerClient({
    keyFilename: serviceAccountJson
  });
  return iotClient;
};
```

Then in the functions, replace the newClient code with:

```node
  const newClient = (client != null) ? client :
      new iot.v1.DeviceManagerClient({ /* optional auth parameters. */ });
```

I'll consider updating the samples, the challenge is that there's some complex code used for testing that would require a refactor if we changed the return type of getClient.

**Comment by sgreenberg** [comment]
It looks like there's an acceptable solution to the problem identified here, and we're no longer making updates to the nodejs IoT samples for bugs with priority 2.
