### ISSUE TITLE
Synthesis failed for iot

### ISSUE THREAD

**Issue by theacodes** [googleapis/nodejs-iot#90]
Hello! Autosynth couldn't regenerate iot. :broken_heart:

Here's the output from running `synth.py`:

```
Cloning into 'working_repo'...
Switched to branch 'autosynth'
Running synthtool
['/Users/theaflowers/workspace/autosynth/env/bin/python3', '-m', 'synthtool', 'synth.py', '--']
synthtool > Executing /Users/theaflowers/workspace/autosynth/working_repo/synth.py.
synthtool > Ensuring dependencies.
synthtool > Pulling artman image.
latest: Pulling from googleapis/artman
Digest: sha256:2f6b261ee7fe1aedf238991c93a20b3820de37a343d0cacf3e3e9555c2aaf2ea
Status: Image is up to date for googleapis/artman:latest
synthtool > Cloning googleapis.
synthtool > Running generator for google/cloud/iot/artman_cloudiot.yaml.
synthtool > Failed executing docker run --name artman-docker --rm -i -e HOST_USER_ID=297975 -e HOST_GROUP_ID=89939 -e RUNNING_IN_ARTMAN_DOCKER=True -v /Users/theaflowers/.cache/synthtool/googleapis:/Users/theaflowers/.cache/synthtool/googleapis -v /Users/theaflowers/.cache/synthtool/googleapis/artman-genfiles:/Users/theaflowers/.cache/synthtool/googleapis/artman-genfiles -w /Users/theaflowers/.cache/synthtool/googleapis googleapis/artman:latest /bin/bash -c artman --local --config google/cloud/iot/artman_cloudiot.yaml generate nodejs_gapic:

docker: Error response from daemon: Conflict. The container name "/artman-docker" is already in use by container "3087920aeb8b0abe58a276685d09ec446834a91d42cd41202a1d55a1a3e1d3ee". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

Traceback (most recent call last):
  File "/Users/theaflowers/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/theaflowers/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/theaflowers/workspace/synthtool/synthtool/__main__.py", line 87, in <module>
    main()
  File "/Users/theaflowers/workspace/autosynth/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/theaflowers/workspace/autosynth/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/theaflowers/workspace/autosynth/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/theaflowers/workspace/autosynth/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/theaflowers/workspace/synthtool/synthtool/__main__.py", line 79, in main
    spec.loader.exec_module(synth_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/theaflowers/workspace/autosynth/working_repo/synth.py", line 27, in <module>
    config_path="/google/cloud/iot/"
  File "/Users/theaflowers/workspace/synthtool/synthtool/gcp/gapic_generator.py", line 46, in node_library
    return self._generate_code(service, version, "nodejs", **kwargs)
  File "/Users/theaflowers/workspace/synthtool/synthtool/gcp/gapic_generator.py", line 116, in _generate_code
    gapic_language_arg,
  File "/Users/theaflowers/workspace/synthtool/synthtool/gcp/artman.py", line 102, in run
    shell.run(cmd, cwd=root_dir)
  File "/Users/theaflowers/workspace/synthtool/synthtool/shell.py", line 39, in run
    raise exc
  File "/Users/theaflowers/workspace/synthtool/synthtool/shell.py", line 33, in run
    encoding="utf-8",
  File "/Users/theaflowers/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'run', '--name', 'artman-docker', '--rm', '-i', '-e', 'HOST_USER_ID=297975', '-e', 'HOST_GROUP_ID=89939', '-e', 'RUNNING_IN_ARTMAN_DOCKER=True', '-v', '/Users/theaflowers/.cache/synthtool/googleapis:/Users/theaflowers/.cache/synthtool/googleapis', '-v', '/Users/theaflowers/.cache/synthtool/googleapis/artman-genfiles:/Users/theaflowers/.cache/synthtool/googleapis/artman-genfiles', '-w', PosixPath('/Users/theaflowers/.cache/synthtool/googleapis'), 'googleapis/artman:latest', '/bin/bash', '-c', 'artman --local --config google/cloud/iot/artman_cloudiot.yaml generate nodejs_gapic']' returned non-zero exit status 125.
synthtool > Cleaned up 0 temporary directories.
synthtool > Wrote metadata to synth.metadata.

Synthesis failed

```

Google internal developers can see the full log [here](https://sponge/None).

**Comment by theacodes** [comment]
Autosynth passed, closing! :green_heart:
